# Generated by Django 3.0.6 on 2020-05-19 14:52

import boards.models
from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sfw', models.BooleanField()),
                ('title', models.CharField(max_length=64)),
                ('slug', models.CharField(max_length=4, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(blank=True, help_text="Required if, 1. current post is parent (thread) and no title is provided or 2. current post is not parent (reply) and no title or file is provided. Main text content/body of current post which appears after it's title.", max_length=2048)),
                ('file', models.FileField(blank=True, help_text='Required if current post is parent (thread). Maximum allowed size is 20MB.', null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='', validators=[boards.models._validate_file_size])),
                ('file_delete_hash', models.CharField(blank=True, help_text='Autopopulated by the system. Will be used to delete uploaded file from imgur.', max_length=64, null=True)),
                ('file_height', models.IntegerField(blank=True, help_text='Autopopulated by the system. Indicates the height of the image file.', null=True)),
                ('file_name', models.CharField(blank=True, default=None, help_text='Autopopulated by the system. The name of the image file.', max_length=256, null=True)),
                ('file_size', models.IntegerField(blank=True, help_text='Autopopulated by the system. Indicates the size of the image file in bytes.', null=True)),
                ('file_url', models.CharField(blank=True, help_text='Autopopulated by the system. Indicates the direct link to the image file.', max_length=64, null=True)),
                ('file_width', models.IntegerField(blank=True, help_text='Autopopulated by the system. Indicates the width of the image file.', null=True)),
                ('ip_address', models.GenericIPAddressField(default='0.0.0.0', help_text='Indicates the ip address of the creator.')),
                ('is_archived', models.BooleanField(default=False, help_text='Indicates whether current post is archived or not.')),
                ('is_locked', models.BooleanField(default=False, help_text='Indicates whether current post is locked or not.')),
                ('is_sticky', models.BooleanField(default=False, help_text='Indicates whether current post is sticky or not.')),
                ('name', models.CharField(blank=True, help_text='Self-given name of the creator.', max_length=32, null=True)),
                ('title', models.CharField(blank=True, help_text='Required if current post is parent (thread) and no body is provided. Title of current post. N.B. replies must not have title.', max_length=64, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('board', models.ForeignKey(help_text='Required. Indicates which board current post belongs to.', on_delete=django.db.models.deletion.CASCADE, to='boards.Board')),
                ('parent', models.ForeignKey(blank=True, help_text='Required. Indicates which parent post (thread) current post (reply) belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.Post')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['is_sticky', '-updated_at'],
            },
        ),
    ]
