# Generated by Django 3.0.6 on 2020-06-13 07:01

import boards.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_auto_20200611_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='file',
            field=models.FileField(blank=True, help_text='Maximum allowed size is 20MB.', null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='', validators=[boards.models._validate_file_size]),
        ),
        migrations.AddField(
            model_name='board',
            name='file_delete_hash',
            field=models.CharField(blank=True, help_text='Autopopulated by the system. Will be used to delete uploaded file from imgur.', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='file_height',
            field=models.IntegerField(blank=True, help_text='Autopopulated by the system. Indicates the height of the image file.', null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='file_name',
            field=models.CharField(blank=True, default=None, help_text='Autopopulated by the system. The name of the image file.', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='file_size',
            field=models.IntegerField(blank=True, help_text='Autopopulated by the system. Indicates the size of the image file in bytes.', null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='file_url',
            field=models.CharField(blank=True, help_text='Autopopulated by the system. Indicates the direct link to the image file.', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='file_width',
            field=models.IntegerField(blank=True, help_text='Autopopulated by the system. Indicates the width of the image file.', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, help_text='Maximum allowed size is 20MB.', null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='', validators=[boards.models._validate_file_size]),
        ),
    ]
