# Generated by Django 3.0.6 on 2020-05-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='quoted_posts',
            field=models.ManyToManyField(related_name='_post_quoted_posts_+', to='boards.Post'),
        ),
    ]
