# Generated by Django 3.0.6 on 2020-05-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_post_quoted_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='quoted_posts',
            field=models.ManyToManyField(related_name='_post_quoted_posts_+', related_query_name='aukrajehr', to='boards.Post'),
        ),
    ]
