# Generated by Django 3.0.6 on 2020-05-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20200527_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='quoted_posts',
            field=models.ManyToManyField(related_name='quote_set', to='boards.Post'),
        ),
    ]
