# Generated by Django 3.0.6 on 2020-05-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_auto_20200527_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='quoted_posts',
            field=models.ManyToManyField(related_name='quoted_in_set', to='boards.Post'),
        ),
    ]
