# Generated by Django 3.0.6 on 2020-06-11 06:12

import boards.models
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_auto_20200527_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='is_sfw',
            field=models.BooleanField(default=False, help_text='Indicates whether this board is safe-for-work (sfw) or not.'),
        ),
        migrations.AlterField(
            model_name='board',
            name='slug',
            field=models.CharField(help_text='Identifier of this board (slug). Will be used in urls.', max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.CharField(help_text='Title of this board.', max_length=64),
        ),
        migrations.AlterField(
            model_name='post',
            name='board',
            field=models.ForeignKey(help_text='Required. Indicates which board this post belongs to.', on_delete=django.db.models.deletion.CASCADE, to='boards.Board'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.CharField(blank=True, help_text="Required if, 1. this post is a thread and no title is provided or 2. this post is a reply and no title or file is provided. Main text content/body of current post which appears after it's title.", max_length=2048),
        ),
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, help_text='Required if this post is a thread. Maximum allowed size is 20MB.', null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='', validators=[boards.models._validate_file_size]),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Indicates whether this post is archived or not.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Indicates whether this post is locked or not.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_sticky',
            field=models.BooleanField(default=False, help_text='Indicates whether this post is sticky or not.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Required. Indicates which thread this post belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, help_text='Required if this post is a thread and no body is provided. Title of this post. N.B. replies must not have title.', max_length=64, null=True),
        ),
    ]
