# Generated by Django 3.0.6 on 2020-06-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_auto_20200613_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='tagline',
            field=models.CharField(blank=True, help_text='Tagline of this board.', max_length=128, null=True),
        ),
    ]
